### ISSUE TITLE
Remember to check the latest version of ACLpub2 

### ISSUE THREAD

**Issue by crux82** [acl-2022/FL4NLP#1]
Dear organizers,

please remember to download the latest version of ACLPUB2 and check the README.
For example, I noticed that the conference_details.yml is not compliant with the new format required by the ACL anthology.

I'm sorry to sound tedious, but it will be difficult to handle the eventual rejection by ACL anthology of even a few of the 28 workshops in ACL2022.

Thank you for your support

**Comment by yuchenlin** [comment]
Thank you! We have updated the format and generated the proceedings based on the latest version.
