### ISSUE TITLE
error when generating the handbook

### ISSUE THREAD

**Issue by yuchenlin** [acl-2022/FL4NLP#2]
When we are doing `aclpub2 % ./bin/generate ../ --handbook --overwrite`

```
Traceback (most recent call last):
  File "/Users/yuchenlin/Documents/.Github.nosync/FL4NLP/aclpub2/./bin/generate", line 32, in <module>
    generate_handbook(args.path, args.overwrite)
  File "/Users/yuchenlin/Documents/.Github.nosync/FL4NLP/aclpub2/aclpub2/generate.py", line 204, in generate_handbook
    ) = load_configs_handbook(root)
  File "/Users/yuchenlin/Documents/.Github.nosync/FL4NLP/aclpub2/aclpub2/generate.py", line 621, in load_configs_handbook
    for workshop in workshops:
TypeError: 'NoneType' object is not iterable
```

**Comment by crux82** [comment]
It is not clear why you are compiling the handbook (for which you do not have the input material, I assume).

The command should be something like `./bin/generate ../ --proceedings --overwrite`

**Comment by yuchenlin** [comment]
I have generated the proceedings successfully and am going to submit them to the publication & workshop chairs. 

I previously got an email asking me to submit the info about the handbook, so I was trying to follow the instructions to generate a handbook. I just read the email again and it seems that I only need to submit the [`program.yml`](https://github.com/acl-2022/FL4NLP/blob/main/program.yml) to the chairs?  

Thank you very much!

**Comment by crux82** [comment]
I see your point. 
You just need to share with the workshop chairs  the `program.yml` and the `papers.yml`
It should be enough. 

Please upload your compressed file with the proceedings on a public repository and then share the link with the publication chair, i.e., me :-)

Thank you for your work!

**Comment by yuchenlin** [comment]
Got it! Thank you very much for your prompt help! I have just sent the email! :)
